services:
  db:
    container_name: todo-list-api-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-todo}
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-list-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-todo}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-admin}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-admin}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: ${JWT_SECRET:-ObJ04G0YHkr3JRjidVA0NTECgewf+Goq3+tGX4gVhxw=}
      JWT_EXPIRATION_MS: 3600000
    restart: on-failure

volumes:
  pgdata:
    driver: local